enabled = true
sendServerConfig = true
sendDistance = true
maxDistance = 96
directionPrecision = 100.0
ticksBetweenUpdates = 5
sneakingHides = true
pumpkinHides = true
mobHeadsHide = true
invisibilityHides = true
visible = true
visibleEmpty = false
acceptServerConfig = true
fadeMarkers = true
fadeStart = 32
fadeEnd = 96
fadeEndOpacity = 0.0
showHeight = false
showHeadsOnTab = true
showNamesOnTab = true
colorMode = "UUID"
constantColor = 0xffffff