name: Release
on: 
  push:
    tags:
      - "v*"


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: checkout
        uses: actions/checkout@v4

      - name: get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: build jar
        run: ./build.py ${{ steps.get_version.outputs.VERSION }}

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          name: trident-${{ github.ref_name }}
          files: |
            Trident Tweaks ${{ steps.get_version.outputs.VERSION }}.jar
          #body_path: RELEASE_NOTES.md
          #draft: true
          make_latest: true